[workspace]
resolver = "3"
members = [
    "backend",
    "data_parsing",
    "frontend",
    "migrations",
    "repository", "search",
    "types",
]

[workspace.package]
version = "0.8.1"
edition = "2024"

[profile.profiling]
inherits = "release"
debug = true
