[workspace]
resolver = "3"
members = [
    "backend",
    "data_parsing",
    "frontend",
    "migrations",
    "repository", "search",
    "types",
]

[profile.profiling]
inherits = "release"
debug = true
