[package]
name = "search"
edition = "2024"
version.workspace = true

[dependencies]
anyhow = "1.0.98"
repository = { path = "../repository" }
serde = { version = "1.0.219", features = ["derive"] }
types = { path = "../types" }
