[package]
name = "search"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
repository = { version = "0.1.0", path = "../repository" }
serde = { version = "1.0.219", features = ["derive"] }
types = { version = "0.1.0", path = "../types" }
