[package]
name = "search"
edition = "2024"
version.workspace = true

[dependencies]
anyhow = "1.0.98"
repository = { version = "0.8.0", path = "../repository" }
serde = { version = "1.0.219", features = ["derive"] }
types = { version = "0.8.0", path = "../types" }
