[package]
name = "migrations"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm = "1.1.19"
sea-orm-migration = { version = "1.1.0", features = ["runtime-tokio-native-tls", "sqlx-postgres"] }
